crud_bj/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reviews.urls")),
]

crud_bj/reviews/urls.py
from django.urls import path
from . import views


app_name = "reviews"
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("edit/<int:pk>", views.edit, name="edit"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("create/", views.create, name="create"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
]

crud_bj/reviews/models.py
from django.db import models


class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

crud_bj/reviews/views.py
from django.shortcuts import render, redirect
from .models import Review


def index(request):
    reviews = Review.objects.all()

    return render(
        request,
        "reviews/index.html",
        {
            "reviews": reviews,
        },
    )


def create(request):
    title = request.GET.get("title")
    content = request.GET.get("content")

    Review.objects.create(title=title, content=content)

    return redirect("reviews:index")


def new(request):
    return render(request, "reviews/new.html")


def edit(request, pk):
    review = Review.objects.get(pk=pk)
    return render(
        request,
        "reviews/edit.html",
        {
            "review": review,
        },
    )


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    return render(
        request,
        "reviews/detail.html",
        {
            "review": review,
        },
    )


def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect("reviews:index")


def update(request, pk):
    review = Review.objects.get(pk=pk)
    title = request.GET.get("title")
    content = request.GET.get("content")

    review.title = title
    review.content = content
    review.save()

    return redirect("reviews:detail", review.pk)

crud_bj/reviews/templates/reviews/detail.html
{% extends 'base.html' %}



{% block content %}

<h1>제목: {{ review.title }}</h1>
<p>{{ review.content }}</p>

<a href="{% url 'reviews:edit' review.pk %}">리뷰 수정</a>
<a href="{% url 'reviews:delete' review.pk %}">리뷰 삭제</a>
  
{% endblock content %}
  

crud_bj/reviews/templates/reviews/edit.html
{% extends 'base.html' %}



{% block content %}
  
  <form action="{% url 'reviews:update' review.pk %}">
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">제목</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="title">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">내용</label>
      <textarea type="text" class="form-control" id="exampleInputPassword1" name="content"></textarea>
    </div>
    <button type="submit" class="btn btn-primary w-100">리뷰 수정</button>
  </form>

{% endblock content %}
  

crud_bj/reviews/templates/reviews/index.html
{% extends 'base.html' %}



{% block content %}

  <div class="new"><a href="{% url 'reviews:new' %}">리뷰 작성</a></div>
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th scope="col">리뷰 번호</th>
        <th scope="col">리뷰 제목</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
    <tbody>
      
      {% for review in reviews %}
      <tr>
        <td>{{ review.id }}</td>
        <td><a href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a></td>
        <td>{{ review.created_at|date:'Y년 m월 d일' }}</td>
      </tr>
      {% endfor %}
        
    </tbody>
  </table>

{% endblock content %}
  

crud_bj/reviews/templates/reviews/new.html
{% extends 'base.html' %}


{% block content %}

  <form action="{% url 'reviews:create' %}">
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">제목</label>
      <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="title">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">내용</label>
      <textarea type="text" class="form-control" id="exampleInputPassword1" name="content"></textarea>
    </div>
    <button type="submit" class="btn btn-primary w-100">리뷰 쓰기</button>
  </form>

{% endblock content %}
  

crud_bj/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" />
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
<div class="container mt-5">
  {% block content %} 
    
  {% endblock content %}  
</div>
</body>
</html>