Practice_JeJoon/practice/urls.py
from django.urls import path
from . import views

app_name = 'practice'

urlpatterns = [
  path('', views.index, name='index'),
  path('create/', views.create, name='create'),
  path('delete/<int:pk>/', views.delete, name='delete'),
  path('edit/<int:pk>/', views.edit, name='edit'),
]

Practice_JeJoon/practiceCRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('practice/', include('practice.urls')),
]

Practice_JeJoon/practice/models.py
from django.db import models

# Create your models here.
class Practice(models.Model):
  title = models.CharField(max_length=80)
  content = models.TextField()
  created_at = models.DateField(auto_now_add=True)
  updated_at = models.DateField(auto_now=True)

Practice_JeJoon/practice/forms.py
from pyexpat import model
from tkinter.tix import Form
from django import forms
from .models import Practice

class practiceForm(forms.ModelForm):

  class Meta:
    model = Practice
    fields = '__all__'

Practice_JeJoon/practice/views.py
from django.shortcuts import render, redirect
from .models import Practice
from .forms import practiceForm

# Create your views here.
def index(request):
  context={
    'saying': Practice.objects.all(),
  }
  return render(request, 'practice/index.html', context)

def create(request):

  if request.method == "POST":
    practice = practiceForm(request.POST)

    if practice.is_valid():
      practice.save()
      return redirect('practice:index')

  else:
    practice_form = practiceForm()
  context = {
    'practice_form' : practice_form,
  }

  return render(request, 'practice/create.html', context)

# def created(request):
#   title = request.GET.get('title')
#   content = request.GET.get('content')

#   Practice.objects.create(title=title, content=content)

#   return redirect('practice:index')

def delete(request, pk):
  Practice.objects.get(id=pk).delete()
  return redirect('practice:index')

def edit(request, pk):
  saying = Practice.objects.get(id=pk)
  
  if request.method == 'POST':
    saying_form = practiceForm(request.POST, instance=saying)

    if saying_form.is_valid():
      saying_form.save()
      return redirect('practice:index')

  else:
    saying_form = practiceForm(instance=saying)
  context = {
    'saying_form': saying_form
  }
  return render(request, 'practice/edit.html', context)

# def edited(request, pk):
#   new_title = request.GET.get('title')
#   new_content = request.GET.get('content')

#   saying = Practice.objects.get(id=pk)

#   saying.title = new_title
#   saying.content = new_content
#   saying.save()

#   redirect('practice:index')

Practice_JeJoon/practice/templates/practice/create.html
{% extends 'base.html' %}

{% block title %}<title>Create</title>{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<h1 class="text-center">Create 페이지 예시</h1>
<form class="container" action="{% url 'practice:create' %}" method="POST">
  {% csrf_token %}
  {{ practice_form.as_p }}

  <div class="image d-flex mb-3">
    <p>이미지 파일</p>
  </div>
  <div class="d-flex mb-3">
    <button type="submit">Upload</button>
  </div>
</form>
{% endblock %}

Practice_JeJoon/practice/templates/practice/edit.html
{% extends 'base.html' %}

{% block title %}<title>Create</title>{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<h1 class="text-center">Create 페이지 예시</h1>
<form class="container" action="" method="POST">
  {% csrf_token %}  
  {{ saying_form.as_p }}

  <div class="image d-flex mb-3">
    <p>이미지 파일</p>
  </div>
  <div class="d-flex mb-3">
    <button type="submit">수정하기</button>
  </div>
</form>
{% endblock %}

Practice_JeJoon/practice/templates/practice/index.html
{% extends 'base.html' %}

{% block title %}<title>Home</title>{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
<h1 class="text-center">Admin Page 예시</h1>
<a href="{% url 'practice:create' %}">명언 추가하기</a>

<div class="container mt-5">
  <h2>재미 명언</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">제목</th>
        <th scope="col">내용</th>
        <th scope="col">이미지</th>
        <th scope="col">변경</th>
        <th scope="col">삭제</th>
      </tr>
    </thead>
    <tbody>
      {% for say in saying %}
      <tr>
        <td>{{ say.title }}</td>
        <td>{{ say.content }}</td>
        <td>이미지</td>
        <td><a href="{% url 'practice:edit' say.pk %}">변경</a></td>
        <td><a href="{% url 'practice:delete' say.pk %}">삭제</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}